# Importando la paquetería.
https://numpy.org/

In [22]:
import numpy as np

# ¿Cómo buscar ayuda desde la libreta de Jupyter?
- <b>Opción 1</b>: Escribir <b>np</b> luego escribir un punto y por último presionar la tecla "<b>TAB</b>" para mostrar diferentes opciones de autocompletado.
- <b>Opción 2</b>: Buscar la documentación incluida con la función "<b>np?</b>"

In [23]:
#np?

# Creando arreglos de números con Numpy.

### Arreglos llenos de ceros.

In [24]:
arreglo = np.zeros(10, dtype = int)
print(arreglo)

[0 0 0 0 0 0 0 0 0 0]


In [25]:
arreglo = np.zeros(10, dtype = bool)
print(arreglo)

[False False False False False False False False False False]


In [26]:
arreglo = np.zeros(10, dtype = float)
print(arreglo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Arreglos llenos de unos.

In [27]:
arreglo = np.ones(10, dtype = int)
print(arreglo)

[1 1 1 1 1 1 1 1 1 1]


In [28]:
arreglo = np.ones(10, dtype = bool)
print(arreglo)

[ True  True  True  True  True  True  True  True  True  True]


In [29]:
arreglo = np.ones(10, dtype = float)
print(arreglo)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Arreglos llenos del mismo valor.

In [30]:
arreglo = np.full(10, 5)
print(arreglo)

[5 5 5 5 5 5 5 5 5 5]


In [31]:
arreglo = np.full(10, "a")
print(arreglo)

['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']


### Arreglos de dos dimensiones.

In [32]:
arreglo = np.full((5, 10), 2)
# Imprimamos el arreglo.
print(arreglo)
print()
# Imprimamos la forma del arreglo.
print(arreglo.shape)
print()
# Imprimamos la cantidad de elementos del arreglo.
print(arreglo.size)

[[2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]]

(5, 10)

50


In [33]:
print(arreglo[0])

[2 2 2 2 2 2 2 2 2 2]


### Arreglos llenos con valores enteros aleatorios.
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html

In [34]:
arreglo = np.random.randint(5,15,40)
print(arreglo)

[14  9 13 11 10  5  7  9  9  6  9  7  8  9  7 10  9  6  6  6  9  7  7 13
  8 10 12  5 11 11 11 11 14 14 13 11 11 13  9  9]


### Arreglos llenos con valores aleatorios entre cero y uno.
https://numpy.org/doc/1.16/reference/generated/numpy.random.random.html

In [35]:
arreglo = np.random.rand(5,5)
print(arreglo)

[[0.68120423 0.02227524 0.84327306 0.0634754  0.01691695]
 [0.26442283 0.05211645 0.25864118 0.12947026 0.56490174]
 [0.33597729 0.39484057 0.89464293 0.77269624 0.45245788]
 [0.42695907 0.81017748 0.04840292 0.92583734 0.49226519]
 [0.37406284 0.3172855  0.16932091 0.17413222 0.29341768]]


### Arreglos llenos con valores uniformemente distribuidos.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

In [36]:
inicio = 0
fin = 5
elementos = 20

In [37]:
x = np.linspace(inicio, fin, elementos)
print(x)

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [38]:
print(x[0])
print(x[1])
print(x[19])

0.0
0.2631578947368421
5.0


$Elemento[0] = 0$
<br>$Elemento[1] = Elemento[0] + 0.26315789473684210526315789473684$
<br>$Elemento[2] = Elemento[1] + 0.26315789473684210526315789473684$
<br>$\vdots$
<br>$Elemento[18] = Elemento[19] + 0.26315789473684210526315789473684$

In [39]:
inicio = 5
fin = 8
elementos = 6

### ¿Cómo calculamos la diferencia entre cada punto?
$\Delta = \frac{fin - inicio}{elementos - 1}$
<br>
<br>$\Delta = \frac{8 - 5}{6 - 1}$
<br>
<br>$\Delta = \frac{3}{5}$
<br>
<br>$\Delta = 0.6$

In [40]:
x = np.linspace(inicio, fin, elementos)
print(x)

[5.  5.6 6.2 6.8 7.4 8. ]


# Cambiando la forma de los arreglos.

In [41]:
x = np.linspace(0, 10, 30)
print(x)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]


In [42]:
print(x.shape) #imprime la forma del arreglo

(30,)


In [43]:
x = x.reshape((15,2)) # cambia la forma del arreglo
print(x)

[[ 0.          0.34482759]
 [ 0.68965517  1.03448276]
 [ 1.37931034  1.72413793]
 [ 2.06896552  2.4137931 ]
 [ 2.75862069  3.10344828]
 [ 3.44827586  3.79310345]
 [ 4.13793103  4.48275862]
 [ 4.82758621  5.17241379]
 [ 5.51724138  5.86206897]
 [ 6.20689655  6.55172414]
 [ 6.89655172  7.24137931]
 [ 7.5862069   7.93103448]
 [ 8.27586207  8.62068966]
 [ 8.96551724  9.31034483]
 [ 9.65517241 10.        ]]


In [44]:
print(x.shape)

(15, 2)


In [45]:
x = x.reshape((5,-1))
print(x)

[[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793]
 [ 2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345]
 [ 4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897]
 [ 6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448]
 [ 8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]]


In [46]:
print(x.shape)

(5, 6)


In [47]:
x = x.reshape((-1,1))
print(x)

[[ 0.        ]
 [ 0.34482759]
 [ 0.68965517]
 [ 1.03448276]
 [ 1.37931034]
 [ 1.72413793]
 [ 2.06896552]
 [ 2.4137931 ]
 [ 2.75862069]
 [ 3.10344828]
 [ 3.44827586]
 [ 3.79310345]
 [ 4.13793103]
 [ 4.48275862]
 [ 4.82758621]
 [ 5.17241379]
 [ 5.51724138]
 [ 5.86206897]
 [ 6.20689655]
 [ 6.55172414]
 [ 6.89655172]
 [ 7.24137931]
 [ 7.5862069 ]
 [ 7.93103448]
 [ 8.27586207]
 [ 8.62068966]
 [ 8.96551724]
 [ 9.31034483]
 [ 9.65517241]
 [10.        ]]


In [48]:
print(x.shape)

(30, 1)


# Haciendo operaciones con arreglos.

In [49]:
x = np.full(5, 10)
y = np.linspace(2, 10, 5)
print(x)
print(y)

[10 10 10 10 10]
[ 2.  4.  6.  8. 10.]


In [50]:
print(x + y)

[12. 14. 16. 18. 20.]


In [51]:
print(x - y)

[8. 6. 4. 2. 0.]


In [52]:
print(x * y)

[ 20.  40.  60.  80. 100.]


In [53]:
print(y**2)

[  4.  16.  36.  64. 100.]


# Algunos operadores disponibles en Numpy
$np.add$
<br>$np.substract$
<br>$np.negative$
<br>$np.multiply$
<br>$np.divide$
<br>$np.power$

In [54]:
print(np.add(x,2))

[12 12 12 12 12]


In [55]:
print(np.power(y,3))

[   8.   64.  216.  512. 1000.]


# Algunas funciones disponibles en Numpy
$np.abs$
<br>$np.sin$
<br>$np.cos$
<br>$np.tan$
<br>$np.exp$
<br>$np.log$

In [56]:
print(np.exp(y))

[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]


In [57]:
print(np.cos(y))

[-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153]


# Algunas funciones de estádistica disponibles en Numpy
$np.min$
<br>$np.max$
<br>$np.std$
<br>$np.var$
<br>$np.median$
<br>$np.percentile$

In [58]:
print(np.max(y))

10.0


In [59]:
print(np.std(y))

2.8284271247461903
